mysql:
  host: ${MYSQL_HOST:mysql}
  port: ${MYSQL_PORT:3306}
  user: ${MYSQL_USER:myuser}
  password: ${MYSQL_PASSWORD:secret}
  database: ${MYSQL_DATABASE:chat_db}

mongodb:
  host: ${MONGODB_HOST:mongodb}
  user: ${MONGODB_USER:admin}
  password: ${MONGODB_PASSWORD:secret}
  database: ${MONGODB_DATABASE:chat_db}

client-base-url: ${CLIENT_BASE_URL:http://localhost:3000}
