version: '3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1-1.23-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  mysql:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=chat_db'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret'
  mongodb:
    image: 'mongo:6.0'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
  rabbitmq:
    image: 'rabbitmq:3.13'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
